// <auto-generated />
using System;
using Assignment_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241030013046_SeedDataMigration")]
    partial class SeedDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_2.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 97,
                            Category = "Other",
                            DateAdded = new DateTime(2024, 10, 29, 19, 30, 45, 757, DateTimeKind.Local).AddTicks(8585),
                            Email = "connor.oiler@gmail.com",
                            Organization = "Oilers",
                            Phone = "9797979797",
                            firstName = "Connor",
                            lastName = "McDavid"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Other",
                            DateAdded = new DateTime(2024, 10, 29, 19, 30, 45, 757, DateTimeKind.Local).AddTicks(8589),
                            Email = "leon.oiler@gmail.com",
                            Organization = "Oilers",
                            Phone = "2929292929",
                            firstName = "Leon",
                            lastName = "Draisaitl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
